name: dashboard_poc
description: A simple project to show Flutter use on the web at Bellum.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  go_router: ^4.5.1
  google_fonts: ^3.0.1
  hydrated_bloc: ^9.0.0-dev.3
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  user_repository:
    path: packages/user_repository
  authentication_repository:
    path: packages/authentication_repository

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  # assets:
  # - assets/
