name: authentication_repository
description: A Dart Repository which manages the authentication domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter_lints: ^2.0.1
  json_annotation: ^4.6.0
  req_res_api:
    path: ../req_res_api

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.0.3
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.16.4
  very_good_analysis: ^3.0.2
